# Generated by Django 2.1.5 on 2020-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200414_2045'),
        ('user', '0003_remove_profile_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
