# Generated by Django 2.1.5 on 2020-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200414_2045'),
        ('user', '0004_profile_user_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_products',
        ),
    ]
