# Generated by Django 2.1.5 on 2020-04-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200416_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_wishlist',
            name='user_products',
        ),
        migrations.DeleteModel(
            name='User_wishlist',
        ),
    ]
