# Generated by Django 2.1.5 on 2020-03-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200322_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category3',
            field=models.CharField(default='', max_length=250),
        ),
    ]
